#!/usr/bin/env bash
# Configure HAProxy load balancer server

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get -y install haproxy

cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" >> /etc/haproxy/haproxy.cfg

balancer="\
frontend haproxy_balancer
        bind *:80
        mode http
        default_backend webservers
    backend webservers
        balance roundrobin
        server 166828-web-01 100.26.222.47:80 check
        server 166828-web-02 35.153.67.249:80 check
"
service haproxy restart
