#!/usr/bin/env bash
# Configuring HAProxy load balancer server

sudo apt-get -y update
sudo apt-get -y upgrade

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

sudo apt-get -y install haproxy=2.5.\*
echo "frontend http
        bind *:80
        mode http
        default_backend web-backend
    backend web-backend
        balance roundrobin
        server 166828-web-01 100.26.222.47:80
        server 166828-web-02 35.153.67.249:80" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
