#!/usr/bin/env bash
# Displays the contents of the current directory in list format.
# where only part of the name after the first dash is displyed
# using the for loop

list=$(ls)
for i in $list; do
  echo "$i" | cut -d '-' -f2
done
