#!/usr/bin/env bash
# configuring nginx user and listening to all active IPs on port 8080
sudo chown /etc/nginx/nginx.conf
sudo chmod u+r /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart


